---
- hosts: all
  tasks:
  - name: Installing Apache
    yum:
      name: httpd
      state: installed
    become: yes
    tags:
      - install
  - name: copying the html file
    copy:
      src: "/home/centos/index.html"
      dest: "/var/www/html"
    become: yes
    tags:
      - copy
  - name: startng apache
    service:
      name: httpd
      state: started
    become: yes
    tags:
      - start
  - name: uninstalling the apche
    yum:
      name: httpd
      state: absent
    become: yes
    tags:
      - uninstall
