---
- hosts: all
  become: true
  vars:
   - tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.53/bin/apache-tomcat-9.0.53.tar.gz
   - tomcat_package: apache-tomcat-9.0.53

  tasks:
  - name: install java for tomcat
    yum:
     name: java
     state : present
  - name: download the tomcat from the official site
    get_url:
      url: "{{ tomcat_url }}"
      dest: /opt
  - name: untar the tomcat package
    unarchive:
      src: /opt/{{ tomcat_package }}.tar.gz
      dest: /opt
      remote_src: True
  -  name: rename the tomcat directory
     command: mv /opt/{{ tomcat_package }}/ /opt/tomcat
  - name: start the tomcat service
    shell: nohup /opt/tomcat/bin/startup.sh